package com.company;

public class Nested_try_catch {
    public static void main(String[] args) {
        int arr[] = {10, 20, 30, 40, 50};
   //     try {
            System.out.println(arr[10]);
     //       try {
                System.out.println(arr[2]);
      //      } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("Exception in level2" );
       //     } catch (Exception e) {
       //     }
            System.out.println("level1 ");
            // System.out.println(e);
            //  }

            //  }
//}
        }
    }
